# Generated by Django 6.0.7 on 2026-07-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Processing', 'Processing'), ('Ready for Pickup', 'Ready for Pickup'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=30),
        ),
    ]
